Update qa-runner-main.yml

diff --git a/.github/workflows/qa-runner-main.yml b/.github/workflows/qa-runner-main.yml
--- a/.github/workflows/qa-runner-main.yml
+++ b/.github/workflows/qa-runner-main.yml
@@ -7,19 +7,15 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    # runs-on: ubuntu-latest
+    runs-on: [qa-frontend-main]
 
     steps:
       - name: 🔄 Checkout code
         uses: actions/checkout@v2
 
-      - name: ⚙️ Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 14
-
       - name: 📦 Install dependencies
-        run: npm install
+        run: npm ci
 
       - name: 🏗️ Build
         run: |
@@ -28,35 +24,38 @@ jobs:
           cat .env
           npm run build
 
-      - name: 🚀 Upload build
-        uses: actions/upload-artifact@v2
-        with:
-          name: static-site
-          path: build/
+      # - name: 🚀 Upload build
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: static-site
+      #     path: build/
 
-  release-project:
-    name: 🚀 Release project
-    runs-on: [qa-frontend-main]
-    needs: build
-    steps:
-      # - name: Cleanup Workspace
-      #   uses: asilbek99/action-cleanup@v1.0
+  # release-project:
+  #   name: 🚀 Release project
+  #   runs-on: [qa-frontend-main]
+  #   needs: build
+    # steps:
+    #   - name: Cleanup Workspace
+    #     uses: asilbek99/action-cleanup@v1.0
+            
+      # - name: Cleanup build folder
+      #   run: |
+      #     ls -la ./
+      #     rm -rf ./* || true
+      #     rm -rf ./.??* || true
+      #     ls -la ./
 
-      - name: Cleanup build folder
-        run: |
-          ls -la ./
-          rm -rf ./* || true
-          rm -rf ./.??* || true
-          ls -la ./
+      # - name: 📥 Download artifact
+      #   uses: actions/download-artifact@v2
+      #   with:
+      #     name: static-site
 
-      - name: 📥 Download artifact
-        uses: actions/download-artifact@v2
-        with:
-          name: static-site
+      # - name: 🧪 Test artifact download
+      #   run: |
+      #     ls -R
 
-      - name: 🧪 Test artifact download
-        run: |
-          ls -R
+    
+          
 
 # Advantages:
 # - ⚙️ Automation: Automates the build and deployment process whenever changes are pushed to the main branch.
